# Site settings
title: ScalABM
email: david.pugh@maths.ox.ac.uk
url: https://scalabm.github.io
description: "A toolkit for developing scalable agent-based models."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: David R. Pugh, Dan F. Tang, and J. Doyne Farmer

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: https://github.com/ScalABM

# Build settings
markdown: kramdown
permalink: pretty
